Add basics tests (incomplete) and "game" util for future use.
gingus55/wordle-react pull request #1
Opened 2022-04-18 01:59 UTC by eLZyBee

2022-04-24 16:40 UTC, gingus55 requested changes
Please remove letterblock.js

2022-04-24 16:40 UTC, gingus55 commented on src/Components/UserInput/UserInput.test.js
> +});
removed user input

2022-04-25 14:17 UTC, eLZyBee commented
Made the changes but now it's almost entirely redundant. Will need to rewrite the tests and extend to the new components.

2026-05-27 12:40 UTC, eLZyBee commented
Cleaning up

2026-05-27 12:40 UTC, closed without merging